# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f7f0f4d5c678c95623db73934a14239fb4fff75ff055629fa2b0ae677b08241b8535c7a8380c41d8c11769393363499d332359fd4f09e5a7e211f8de5bb0a98

test:
  secret_key_base: 48182710438e074658c0358ff2076543ef25a4c8d30ffdd1505a956cc03d6ff6747d64d9d62568cb26a941c48e2012ee454f8aeb12c39c8f75178035ee5093ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
